var app = angular.module('afmcr', []);

// app.controller('Events', function($scope, $http) {
//     $http.get('http://mafn.herokuapp.com/api/events').
//         then(function(response) {
//             $scope.event_list = response.data;
//         });
// });

app.controller('Events', ['$scope', function($scope) {
  $scope.event_list = event_list
}]);

app.controller('test', ['$scope', function($scope) {
  $scope.title = 'Angular Title';
}]);


var event_list = [  {
    "id": 1,
    "name": "Age Friendly Hulme & Moss Side Drop In",
    "category": "partnership",
    "start": "2016-05-26T10:00:00.000Z",
    "description": "Come and chat with members of the Age Friendly Hulme & Moss Side board and Manchester Age Friendly Neighbourhood team. ",
    "created_at": "2016-07-18T17:26:47.419Z",
    "updated_at": "2016-07-18T17:26:47.419Z",
    "entity_id": 1,
    "finish": "2016-05-26T12:00:00.000Z",
    "google_id": "h49di6vhm0mda6noddhm3240q8@google.com",
    "location": "Millennium Powerhouse Library",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 2,
    "name": "Coffee Cake & Culture",
    "category": "partnership",
    "start": "2016-06-30T13:00:00.000Z",
    "description": "We offer fully supported museum visits for people living with dementia and their family member or carer. \n\nThis is a free session on the last Thursday of the month from 2pm - 4pm.\n\nFor further info plrase contact Wendy Gallagher:\nwendy.gallagher@manchester.ac.uk or call 07920 595772",
    "created_at": "2016-07-18T17:26:47.447Z",
    "updated_at": "2016-07-18T17:26:47.447Z",
    "entity_id": 2,
    "finish": "2016-06-30T15:00:00.000Z",
    "google_id": "cgg9mhh047lsqggd78llp4jac8@google.com",
    "location": "Whitworth Art Gallery, Oxford Rd, Manchester M15 6ER, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 3,
    "name": "Walking for Health",
    "category": "partnership",
    "start": "2016-06-29T11:30:00.000Z",
    "description": "Walking is great for your well-being and puts a spring in your step. With this event you can take part in free short art walks at Whitworth Park to help you get active at a pace that works for you.\n\nIt's an excellent way to stretch your legs, explore what's on your door-step, and make new friends.\n\nJoin us every Wednesday lunchtime 12.30pm - 1.30pm for a walk in the park. We meet at the park entrance reception of the gallery.\n\nFor more info pleas econtact whitworth@manchester.ac.uk or call 0161 275 7450",
    "created_at": "2016-07-18T17:26:47.465Z",
    "updated_at": "2016-07-18T17:26:47.465Z",
    "entity_id": 3,
    "finish": "2016-06-29T12:30:00.000Z",
    "google_id": "5fv1n8mjfsdi4r90g4kn8qv68s@google.com",
    "location": "Whitworth Art Gallery, Oxford Rd, Manchester M15 6ER, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 4,
    "name": "Community Learning Festival",
    "category": "partnership",
    "start": "2016-07-27T00:00:00.000Z",
    "description": "This Community Learning Festival consists of four days of workshops, speakers and events to inspire and support many types of learning. It will also provide a space to build connections between people, and between the University and our local community.\n\nWednesday: Theme - Care and Creativity\nAll afternoon Community Games Tepee and Parachute\n12 noon Hidden Voices of Hulme - workshop performance\n1.00pm - 2.30pm Looking After Ourselves? Discussion on sex and healthy relationships led\nby Jayne Mugglestone and Jayshree Henry (Age 14+)\n1.00pm - 4.00pm Womenâ€™s Comedy workshops run by Natalie Diddams - Royal Exchange\n(Age 18+)\n1.00pm - 4.00pm Promoting Positive Sexual Health: Focus on testicular cancer and young\nmen (Age 14+)\n1.00pm - 4.00pm Storytelling workshops:\nâ€¢ Petrus Homelessness Project and Digital Arts North West (all ages)\nâ€¢ LGBT storytelling workshop led by The Proud Trust\nâ€¢ Mobile Phone story telling led by Imran (young people focus)\nâ€¢ Under 8â€™s and Under 12â€™s sessions led by Libraries\n1.00pm - 4.00pm Exploring Boys Work: Voluntary Youth Manchester Boys Work Network\n2.00pm - 5:00pm Showing of the films Paddington and Inside Out followed by discussions\n3.00pm - 4.00pm All age workshop on the Citizen App with Kevin Jones and Caleb Jackson\n4.00pm - 5.00pm Hideaway films on harassment of Muslim girls and women, plus\ndiscussion (young people focus)\n4.00pm - 5.00pm Being young and being a part of the whole world: Workshop led by\nHebe\n5.00pm - 6.00pm Public Lecture with Gabrielle Ivinson: Poverty, Community and\nEducation, lecture and discussioin\n6.00pm - 7.00pm Hidden Voices of Hulme performance\n\nTo keep up to date with the festival please subscribe to our email list here.\nhttp://eepurl.com/bOjsCn\n\nThe festival will run from 26th-29th July, to get involved in the planning of the event please email edlab@mmu.ac.uk letting us know how you or your group would want to contribute.",
    "created_at": "2016-07-18T17:26:47.887Z",
    "updated_at": "2016-07-18T17:26:47.887Z",
    "entity_id": 4,
    "finish": "2016-07-28T00:00:00.000Z",
    "google_id": "qnf08lj9b00flficarv8d3ruek@google.com",
    "location": "Brooks Building, Birley, Bonsall St, Manchester M15",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 5,
    "name": "Community Learning Festival",
    "category": "partnership",
    "start": "2016-07-28T00:00:00.000Z",
    "description": "This Community Learning Festival consists of four days of workshops, speakers and events to inspire and support many types of learning. It will also provide a space to build connections between people, and between the University and our local community.\n\nThursday: Theme - Environment and Sustainability\nAll afternoon Stalls and Bike Bonanza\n12.00pm - 1.30pm Tony Curry writing workshops: RAP on the theme of environment and\nsustainability\n12.00pm - 1.30pm Hulme Community Garden Centre workshop: Pond dipping, herbs and\nmuch more\n2.00pm - 3.30pm Asset based working workshop: sustainable community development\nled by Eve Davidson\n2.00pm - 3.30pm Tony Curry writing workshops: RAP on the theme of environment and\nsustainability\n2.00pm - 3.30pm Carbon literacy course introduction\n2.00pm - 3.30pm Hulme Community Garden Centre: permaculture\n2.00pm - 3.30pm Site tours: learn about the Birley Campus as a â€˜green campus\n4.00pm - 5.00pm Geoff Bright Presentation: â€˜The Ladyâ€™s not for Burning? May she Rust\nin Peace: Ghostly Presences and Social Hauntings from the Minerâ€™s Strike\n1984-5 in South Yorkshire.â€™\n4.00pm - 5.30pm Just eat it? (film)\n6.00pm - 7.00pm Public lecture: â€˜Tale of Two Citiesâ€™ talk - issues of sustainability in\nManchester\n6.00pm - 7.00pm Transport in Hulme: Talks and discussion with Transport for Greater\nManchester, Manchester City Council and Manchester Metropolitan\nUniversity\n\nTo keep up to date with the festival please subscribe to our email list here.\nhttp://eepurl.com/bOjsCn\n\nThe festival will run from 26th-29th July, to get involved in the planning of the event please email edlab@mmu.ac.uk letting us know how you or your group would want to contribute.",
    "created_at": "2016-07-18T17:26:47.901Z",
    "updated_at": "2016-07-18T17:26:47.901Z",
    "entity_id": 5,
    "finish": "2016-07-29T00:00:00.000Z",
    "google_id": "1m6sqc6pd793fm81jpstg02qgk@google.com",
    "location": "Brooks Building, Birley, Bonsall St, Manchester M15",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 6,
    "name": "Cycling in an Age Friendly Hulme & Moss Side?",
    "category": "partnership",
    "start": "2016-07-04T13:00:00.000Z",
    "description": "Are you over 50? \nDo you cycle in Hulme & Moss Side?\nOr do you want to cycle more? \nWe want to talk to you! \nWe would like to find out what itâ€™s like to cycle in your neighbourhood, and to talk about ways to encourage more older people to cycle!\n\nCome along to the workshop to find out more:\nMonday 4th July, 2pm - 4pm\nCity South HQ, Turing House\nArchway 5, Hulme, Manchester M15 5RL\n\nRefresments wil be available\n\nEveryone welcome, but please RSVP:\nEmily Crompton, Manchester Age Friendly Neighbourhoods (MAFN)\n0161 247 5960 or 07973 973184\ne.crompton@mmu.ac.uk\n",
    "created_at": "2016-07-18T17:26:47.925Z",
    "updated_at": "2016-07-18T17:26:47.925Z",
    "entity_id": 6,
    "finish": "2016-07-04T15:00:00.000Z",
    "google_id": "ov3rhu6qnntb69p8hrf78lhu50@google.com",
    "location": "City South HQ, Turing House,Archway 5, Hulme, Manchester M15 5RL",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 7,
    "name": "WoW - Cancer Support Group",
    "category": "partnership",
    "start": "2016-06-01T12:15:00.000Z",
    "description": "Women only Wednesdays Cancer Support\nAre you a woman? Have you or anyone else close to you been affected by cancer? Would you like to meet other women in a similar position?\n\nWhat do we offer?\n- regular meetings where you can chat with others and share experiences.\n- Health and well-being therapies (relaxation, massage, reflexology)\n- Structured cancer related workshops, i.e. managing fatigue, stress and anxiety.\n- Advice and tips on how to manage both practical and emotional issues.\nWe meet on the first Wednesday of every month at Kath Locke Centre from 1.15 - 3.15pm.\n\nThis project is targeted at, but not exclusive to BME and marginilised women living in Hulme, Moss Side, Old Trafford, Levenshulme, Chorlton and surrounding areas.\n\nAll activities and workshops are delivered by qualified and experienced individuals. Activities are free and refreshments are provided. We welcome women who are carers, family and friends (over 18 years) of people with cancer.\n\nFor more information contact Marcella: 07496 089310, email: info@can-survive.org.uk \nhttp://www.can-survive.org.uk/",
    "created_at": "2016-07-18T17:26:47.939Z",
    "updated_at": "2016-07-18T17:26:47.939Z",
    "entity_id": 7,
    "finish": "2016-06-01T14:15:00.000Z",
    "google_id": "jmbsmjit50j5jjb64iukr1dek4@google.com",
    "location": "Kath Locke Centre, 123 Moss Ln E, Manchester, Manchester M15 5DD, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 16,
    "name": "Living Medicine - Self Care With Food & Herbs: Skin & First Aid",
    "category": "partnership",
    "start": "2016-09-18T12:00:00.000Z",
    "description": "The course Includes discussion, practical remedy making, handouts and freebies; the course will help you to assess your health and diet and to make positive changes and healthier food choices for you and your family. \nAll sessions assume no prior knowledge and are open to anyone who is interested in improving their health choices and knowledge of traditional plant medicine and nutrition. \n\nThis course will be held on every third Sunday of the month, June to October from 1-4pm. \n\nfor more Info contact Jane Placca 07944 916196 themanchesterherbalist@yahoo.com \nFacebook: Living Medicine Manchester ",
    "created_at": "2016-07-18T17:26:48.102Z",
    "updated_at": "2016-07-18T17:26:48.102Z",
    "entity_id": 16,
    "finish": "2016-09-18T15:00:00.000Z",
    "google_id": "ngd2fv2lnasrj41e7vg17nc6ts@google.com",
    "location": "Hulme Community Garden Centre, 28 Old Birley St, St. George's, Manchester M15 5RG, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 17,
    "name": "Home Business Workshop",
    "category": "partnership",
    "start": "2016-06-30T08:30:00.000Z",
    "description": "Thursday 30th June 2016 9.30 - 4.00pm\nHome Business Workshop\nVenue: St Wilfred's Enterprise Centre\n(FirmStart) Royce Road Hulme M15 4BJ\n\nFor further details contact: Richard at ABS (Amazin Business Solutions) on 07590425644 or 079271 43531\nemail: info@amazinbusinesssolutions.com\n",
    "created_at": "2016-07-18T17:26:48.116Z",
    "updated_at": "2016-07-18T17:26:48.116Z",
    "entity_id": 17,
    "finish": "2016-06-30T15:00:00.000Z",
    "google_id": "qf5fc9dg568av72idmsde44ki0@google.com",
    "location": "St Wilfred's Enterprose Centre",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 8,
    "name": "MOT - Cancer Support Group",
    "category": "partnership",
    "start": "2016-06-30T12:00:00.000Z",
    "description": "Men Only Thursdays - Cancer Support Group\n Are you a man? Have you or anyone else close to you been affected by cancer? Would you like to meet other men in a similar position?\n\nWhat do we offer?\n- regular meetings where you can chat with others and share experiences.\n- Health and well-being therapies (relaxation, massage, reflexology)\n- Structured cancer related workshops, i.e. managing fatigue, stress and anxiety.\n- Advice and tips on how to manage both practical and emotional issues.\nWe meet on the first Wednesday of every month at Kath Locke Centre from 1.15 - 3.15pm.\n\nThis project is targeted at, but not exclusive to BME and marginilised men living in Hulme, Moss Side, Old Trafford, Levenshulme, Chorlton and surrounding areas.\n\nAll activities and workshops are delivered by qualified and experienced individuals. Activities are free and refreshments are provided. We welcome men who are carers, family and friends (over 18 years) of people with cancer.\n\nFor more information contact Marcella: 07496 089310, email: info@can-survive.org.uk \nhttp://www.can-survive.org.uk/",
    "created_at": "2016-07-18T17:26:47.958Z",
    "updated_at": "2016-07-18T17:26:47.958Z",
    "entity_id": 8,
    "finish": "2016-06-30T14:00:00.000Z",
    "google_id": "dl1jkjo7ksf5n20gk9i9nledfg@google.com",
    "location": "Kath Locke Centre, 123 Moss Ln E, Manchester, Manchester M15 5DD, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 9,
    "name": "Queens Birthday Community Social",
    "category": "partnership",
    "start": "2016-06-10T17:00:00.000Z",
    "description": "Community Social Event at St James, quiz, food and music from 40s and 50s - Invite your friends and neighbours!",
    "created_at": "2016-07-18T17:26:47.976Z",
    "updated_at": "2016-07-18T17:26:47.976Z",
    "entity_id": 9,
    "finish": "2016-06-10T20:00:00.000Z",
    "google_id": "ujbcmaotadn0e6impbkb0us0fo@google.com",
    "location": "St James, 95a Princess Road/ Great Western Street, M14 4TH",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 10,
    "name": "LINK Arts and Crafts",
    "category": "partnership",
    "start": "2016-06-13T12:30:00.000Z",
    "description": "Every Wednesday our Arts & Crafts group meets for a two hour session of experimenting with different art techniques, from painting and drawing to textile work. All sessions are run by trained artists and all materials are provided.\n\nSessions cost 50p, and there is no need to book ahead.\n\nWe meet at 1.30pm each week at Trinity House or, on the last Wednesday of each month, at the Gallery of Costume, Platt Hall, Platt Fields Park (just across Platt Lane from Trinity House).\n\nWhatever your level of ability youâ€™ll be welcomed into our friendly group and go home with your very own masterpiece!\n\nSee website for more details: http://www.trinityhousecrc.org.uk/ \n\nContact Trinity House on 0161 225 1064",
    "created_at": "2016-07-18T17:26:47.990Z",
    "updated_at": "2016-07-18T17:26:47.990Z",
    "entity_id": 10,
    "finish": "2016-06-13T14:00:00.000Z",
    "google_id": "0g774tu1t9v058qgoufpc8c5ks@google.com",
    "location": "Trinity House Community Resource Centre, Grove Close, Manchester, M14 5AA",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 11,
    "name": "Coffee and Computing",
    "category": "partnership",
    "start": "2016-06-10T13:00:00.000Z",
    "description": "Coffee and Computing sessions run to help local people get online and understand how to use the internet. Sessions are open to people of all abilities, whether youâ€™ve used a computer before or not. If you know someone whoâ€™s like to get online for the first time, why not pass the message on. We have volunteers ready and willing to talk you through simple activities in basic computer use, email and social networking. All sessions are free of charge and there is no need to book, although the number of computers available is limited.\n\nIf you would like more information about these sessions please contact Brian or call 0161 225 1064 or check the website: http://www.trinityhousecrc.org.uk/ ",
    "created_at": "2016-07-18T17:26:48.007Z",
    "updated_at": "2016-07-18T17:26:48.007Z",
    "entity_id": 11,
    "finish": "2016-06-10T15:00:00.000Z",
    "google_id": "kkc52m5afs9jsdpb9kgfsf5kc4@google.com",
    "location": "Trinity House Community Resource Centre, Grove Close, Manchester M14 5AA, ",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 12,
    "name": "Living Medicine - Self Care With Food & Herbs: Sleep, Anxiety & Fatigue",
    "category": "partnership",
    "start": "2016-08-21T12:00:00.000Z",
    "description": "The course Includes discussion, practical remedy making, handouts and freebies; the course will help you to assess your health and diet and to make positive changes and healthier food choices for you and your family. \nAll sessions assume no prior knowledge and are open to anyone who is interested in improving their health choices and knowledge of traditional plant medicine and nutrition. \n\nThis course will be held on every third Sunday of the month, June to October from 1-4pm. \n\nfor more Info contact Jane Placca 07944 916196 themanchesterherbalist@yahoo.com \nFacebook: Living Medicine Manchester ",
    "created_at": "2016-07-18T17:26:48.026Z",
    "updated_at": "2016-07-18T17:26:48.026Z",
    "entity_id": 12,
    "finish": "2016-08-21T15:00:00.000Z",
    "google_id": "5b711gari6f4ta74phatg9q6b0@google.com",
    "location": "Hulme Community Garden Centre, 28 Old Birley St, St. George's, Manchester M15 5RG, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 13,
    "name": "Living Medicine - Self Care With Food & Herbs: Digestion Discomfort",
    "category": "partnership",
    "start": "2016-07-17T12:00:00.000Z",
    "description": "The course Includes discussion, practical remedy making, handouts and freebies; the course will help you to assess your health and diet and to make positive changes and healthier food choices for you and your family. \nAll sessions assume no prior knowledge and are open to anyone who is interested in improving their health choices and knowledge of traditional plant medicine and nutrition. \n\nThis course will be held on every third Sunday of the month, June to October from 1-4pm. \n\nfor more Info contact Jane Placca 07944 916196 themanchesterherbalist@yahoo.com \nFacebook: Living Medicine Manchester ",
    "created_at": "2016-07-18T17:26:48.046Z",
    "updated_at": "2016-07-18T17:26:48.046Z",
    "entity_id": 13,
    "finish": "2016-07-17T15:00:00.000Z",
    "google_id": "c829tkand8je0mjv4euthm3pqk@google.com",
    "location": "Hulme Community Garden Centre, 28 Old Birley St, St. George's, Manchester M15 5RG, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 14,
    "name": "Living Medicine- Self Care With Food & Herbs: Self Care",
    "category": "partnership",
    "start": "2016-06-19T12:00:00.000Z",
    "description": "The course Includes discussion, practical remedy making, handouts and freebies; the course will help you to assess your health and diet and to make positive changes and healthier food choices for you and your family. \nAll sessions assume no prior knowledge and are open to anyone who is interested in improving their health choices and knowledge of traditional plant medicine and nutrition. \n\nThis course will be held on every third Sunday of the month, June to October from 1-4pm. \n\nfor more Info contact Jane Placca 07944 916196 themanchesterherbalist@yahoo.com \nFacebook: Living Medicine Manchester ",
    "created_at": "2016-07-18T17:26:48.065Z",
    "updated_at": "2016-07-18T17:26:48.065Z",
    "entity_id": 14,
    "finish": "2016-06-19T15:00:00.000Z",
    "google_id": "hgusihru1oqcceot64llt3ldao@google.com",
    "location": "Hulme Community Garden Centre, 28 Old Birley St, St. George's, Manchester M15 5RG, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 15,
    "name": "Living Medicine - Self Care With Food & Herbs: Coughs, Colds & Allergies",
    "category": "partnership",
    "start": "2016-10-16T12:00:00.000Z",
    "description": "The course Includes discussion, practical remedy making, handouts and freebies; the course will help you to assess your health and diet and to make positive changes and healthier food choices for you and your family. \nAll sessions assume no prior knowledge and are open to anyone who is interested in improving their health choices and knowledge of traditional plant medicine and nutrition. \n\nThis course will be held on every third Sunday of the month, June to October from 1-4pm. \n\nfor more Info contact Jane Placca 07944 916196 themanchesterherbalist@yahoo.com \nFacebook: Living Medicine Manchester ",
    "created_at": "2016-07-18T17:26:48.077Z",
    "updated_at": "2016-07-18T17:26:48.077Z",
    "entity_id": 15,
    "finish": "2016-10-16T15:00:00.000Z",
    "google_id": "h29b18095v4c463gok5kphmin4@google.com",
    "location": "Hulme Community Garden Centre, 28 Old Birley St, St. George's, Manchester M15 5RG, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 18,
    "name": "Swim for Adults",
    "category": "partnership",
    "start": "2016-05-22T08:00:00.000Z",
    "description": "This is a swimming session adults only, aged 16 and over. \n\nYou can swim for free if you are over 60 and a resident of Manchester. Take along a document with proof of date of birth and a utilities bill showing you are a Manchester resident.\n\nPrice: Â£2.50 or with a Manchester Leisure Pass Â£2 (peak times) Â£1.70 (off peak times: 9am-12 and 2-5pm). Free if over 60.\n\nNo Booking required. Just come along at the times listed and enjoy your swim in our pool - note that swim safely rules do apply.\n\nSee here for more: http://www.better.org.uk/venues/moss-side/timetable/pool",
    "created_at": "2016-07-18T17:26:48.136Z",
    "updated_at": "2016-07-18T17:26:48.136Z",
    "entity_id": 18,
    "finish": "2016-05-22T09:00:00.000Z",
    "google_id": "r5b0df1l32l7vng8a5755ngv14@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 19,
    "name": "Swim for Adults",
    "category": "partnership",
    "start": "2016-05-30T05:30:00.000Z",
    "description": "This is a swimming session adults only, aged 16 and over. \n\nYou can swim for free if you are over 60 and a resident of Manchester. Take along a document with proof of date of birth and a utilities bill showing you are a Manchester resident.\n\nPrice: Â£2.50 or with a Manchester Leisure Pass Â£2 (peak) Â£1.70 (off peak 9am-12 and 2-5pm). Free if over 60.\n\nNo Booking required. Just come along at the times listed and enjoy your swim in our pool - note that swim safely rules do apply.\n\nSee here for more: http://www.better.org.uk/venues/moss-side/timetable/pool",
    "created_at": "2016-07-18T17:26:48.155Z",
    "updated_at": "2016-07-18T17:26:48.155Z",
    "entity_id": 19,
    "finish": "2016-05-30T09:00:00.000Z",
    "google_id": "lm7ish2sov1mjovp61aujepf8g@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 20,
    "name": "Dementia Friendly Swimming",
    "category": "partnership",
    "start": "2016-06-08T12:00:00.000Z",
    "description": "Dementia Friendly Swimming session for people affected by dementia - either as a carer or someone living with the condition.\n\nThe session is Â£1 for anyone under 60 or from outside of the City of Manchester boundaries â€“ otherwise the session is free (thanks to the free swimming for Over 60s offer and the centreâ€™s Carers Scheme) - please bring proof of age and address.\n\nThe group offer support with Transport in partnership with Manchester Community Transport. So please do get in touch if you require transport in order to get to the session.\n\nContact Catriona Sudlow for queries/ to arrange transport: 07583 134810",
    "created_at": "2016-07-18T17:26:48.176Z",
    "updated_at": "2016-07-18T17:26:48.176Z",
    "entity_id": 20,
    "finish": "2016-06-08T13:00:00.000Z",
    "google_id": "4m4spa75ds0loljkd8lfig1eo0_R20160608T120000@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 21,
    "name": "Dementia Friendly Swimming",
    "category": "partnership",
    "start": "2016-06-01T12:00:00.000Z",
    "description": "Dementia Friendly Swimming session for people with dementia and carers.",
    "created_at": "2016-07-18T17:26:48.203Z",
    "updated_at": "2016-07-18T17:26:48.203Z",
    "entity_id": 21,
    "finish": "2016-06-01T13:00:00.000Z",
    "google_id": "4m4spa75ds0loljkd8lfig1eo0@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 22,
    "name": "Swim For Adults",
    "category": "partnership",
    "start": "2016-05-26T05:30:00.000Z",
    "description": "This is a swimming session adults only, aged 16 and over. \n\nYou can swim for free if you are over 60 and a resident of Manchester. Take along a document with proof of date of birth and a utilities bill showing you are a Manchester resident.\n\nPrice: Â£2.50 or with a Manchester Leisure Pass Â£2 (peak) Â£1.70 (off peak 9am-12 and 2-5pm). Free if over 60.\n\nNo Booking required. Just come along at the times listed and enjoy your swim in our pool - note that swim safely rules do apply.\n\nSee here for more: http://www.better.org.uk/venues/moss-side/timetable/pool",
    "created_at": "2016-07-18T17:26:48.216Z",
    "updated_at": "2016-07-18T17:26:48.216Z",
    "entity_id": 22,
    "finish": "2016-05-26T08:00:00.000Z",
    "google_id": "bdrspt61u2ebmv2p8m5iu39r2g@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 23,
    "name": "Swim for Adults",
    "category": "partnership",
    "start": "2016-05-29T15:00:00.000Z",
    "description": "This is a swimming session adults only, aged 16 and over. \n\nYou can swim for free if you are over 60 and a resident of Manchester. Take along a document with proof of date of birth and a utilities bill showing you are a Manchester resident.\n\nPrice: Â£2.50 or with a Manchester Leisure Pass Â£2 (peak times) Â£1.70 (off peak times: 9am-12 and 2-5pm). Free if over 60.\n\nNo Booking required. Just come along at the times listed and enjoy your swim in our pool - note that swim safely rules do apply.\n\nSee here for more: http://www.better.org.uk/venues/moss-side/timetable/pool",
    "created_at": "2016-07-18T17:26:48.231Z",
    "updated_at": "2016-07-18T17:26:48.231Z",
    "entity_id": 23,
    "finish": "2016-05-29T16:00:00.000Z",
    "google_id": "qbjpoujo1qkc70bjgjdf8q8qro@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 24,
    "name": "Summer Community Games",
    "category": "partnership",
    "start": "2016-07-23T00:00:00.000Z",
    "description": "",
    "created_at": "2016-07-18T17:26:48.250Z",
    "updated_at": "2016-07-18T17:26:48.250Z",
    "entity_id": 24,
    "finish": "2016-08-21T00:00:00.000Z",
    "google_id": "90p7ccilqtvco3akf0kkkmtaj4@google.com",
    "location": "Brooks, Birley, 53 Bonsall Street Manchester M15 6GX",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 25,
    "name": "Sing Along BBC MUSIC DAY",
    "category": "partnership",
    "start": "2016-06-03T08:45:00.000Z",
    "description": "We will be arriving at 9.45am and sing at 10.30am\nWe are singing Put a Little Love In Your Heart voices only \nDress code blue and white\n\nContact Sally Ferris,  Together Dementia Support\n07854 335890\n",
    "created_at": "2016-07-18T17:26:48.266Z",
    "updated_at": "2016-07-18T17:26:48.266Z",
    "entity_id": 25,
    "finish": "2016-06-03T11:00:00.000Z",
    "google_id": "3bsivkij8er2fu0ldvbso6fefg@google.com",
    "location": "EPPING WALK BRIDGE located at MMU Bonsall St Hulme Manchester M15 6GX",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 35,
    "name": "Hulme Library",
    "category": "partnership",
    "start": "2016-04-22T12:00:00.000Z",
    "description": "Hulme had the very first branch library of Manchesterâ€™s free library â€“ which was itself the countryâ€™s first free library!\n\nAssistance Available:\nMondays: 1â€“5pm\nTuesdays: 9amâ€“1pm\nWednesdays: 1â€“8pm\nThursdays: 9am-1pm\nFridays: 1â€“5pm\nSaturdays: 9am-1pm & 2â€“5pm\nBank holidays we are closed.\n\nThere is underground car parking\n\nThe library will be open the same hours as the leisure centre and you will be able to:\nbrowse & borrow a selection of popular books;\nreturn & renew books;\nlog on to internet-ready PCs; and \ncollect reservations.\nContact: 0161 227 3739 or hulmelibrary@manchester.gov.uk",
    "created_at": "2016-07-18T17:26:48.485Z",
    "updated_at": "2016-07-18T17:26:48.485Z",
    "entity_id": 35,
    "finish": "2016-04-22T16:00:00.000Z",
    "google_id": "v551f81seite6h1hsdn5k9i8j8@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 36,
    "name": "World Family Picnic European City of Science ",
    "category": "partnership",
    "start": "2016-06-12T00:00:00.000Z",
    "description": "On Sunday 12th June, we will be hosting a community picnic at Birley as part of the national Big Lunch, an annual event aimed at bringing people together and celebrating community.\nThe event will be linked to Manchesterâ€™s status as European City of Science 2016 and will have avery special science theme.\nIn partnership with the Faculty of Science and Engineering, MetMUnch, the Universityâ€™s Environment Team, and local community partners weâ€™ll be showcasing fermented foods made out of microbes and invite you to take part and bring your own picnic. Thereâ€™ll be plenty of family-friendly activities and you can find out more about the Birley Community Orchard and herb garden.  \nFor more information on how to get involved contact: engagement@mmu.ac.uk or 0161 247 3393",
    "created_at": "2016-07-18T17:26:48.502Z",
    "updated_at": "2016-07-18T17:26:48.502Z",
    "entity_id": 36,
    "finish": "2016-06-13T00:00:00.000Z",
    "google_id": "rdibmc8jc9k33iu03iat93bb14@google.com",
    "location": "Birley Fields, Bonsall St, Manchester M15, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 52,
    "name": "Carers Support drop in (1st Thursday of the month)",
    "category": "partnership",
    "start": "2016-04-07T10:30:00.000Z",
    "description": "\n 11.30am at the Windrush Millennium Centre\nSupport, trips, short breaks, information/advice, respite alternative treatments, practical help.\nTel: 0161 226-9562\nFax: 0161 226-7947\nEmail: admin@acmhs-blackmentalhealth.org.uk\nWeb: www.acmhs-blackmentalhealth.org.uk\n\n",
    "created_at": "2016-07-18T17:26:48.782Z",
    "updated_at": "2016-07-18T17:26:48.782Z",
    "entity_id": 52,
    "finish": "2016-04-07T16:00:00.000Z",
    "google_id": "m49bh1kfp1lad70icrh0egqotg@google.com",
    "location": "Windrush Drive, Windrush Dr, Manchester, Manchester M9 5QR, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 53,
    "name": "Women's Group",
    "category": "partnership",
    "start": "2016-03-08T13:00:00.000Z",
    "description": "Advice, information, discussion, support\nTel: 0161 226-9562\nFax: 0161 226-7947\nEmail: admin@acmhs-blackmentalhealth.org.uk\nWeb: www.acmhs-blackmentalhealth.org.uk\n",
    "created_at": "2016-07-18T17:26:48.798Z",
    "updated_at": "2016-07-18T17:26:48.798Z",
    "entity_id": 53,
    "finish": "2016-03-08T15:00:00.000Z",
    "google_id": "ajmngp86a2h662ifdsgqa19g1o@google.com",
    "location": "Windrush Millennium Centre, Alexandra Rd, Manchester, Manchester M16 7WD, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 26,
    "name": "Manchester & District Orienteering Club event",
    "category": "partnership",
    "start": "2016-07-10T00:00:00.000Z",
    "description": "Contact Manchester and District Orienteering Club for more details: http://www.mdoc.org.uk/ \n\ntwinpeak2016@mdoc.org.uk \n\nVenue\nSouthern and Central Manchester\n\nTravel\nPublic Transport: 2km from Piccadilly to Assembly. Frequent bus services with walk of about 200m from nearest stops.\n\nAssembly\nManchester Metropolitan University, MMU Birley Campus, near A5103 Princess Road, Hulme. Postcode M15 6GX. GR SJ836965.\n\nParking\nWithin 200m of Assembly.\n\nDogs\nDogs will not be welcome on the Campus. Nearby public parking is available\n\nFacilities\nToilets, showers, lockers, snack bar. Traders (possibly)\n\nEntry\nEnter online via SI Entries - open from April 14th. Enter by course letter, A to G.\n\nSelect Edit entries to amend your entry, or Entry list to view current entries.\n\nAll pre-entered competitors will use SI Air Cards, with contactless punching.\nFor those entering Day 2 only, cards will be available for collection at Assembly at MMU\n\nClosing Date\nJune 26th. Possible late entry until July 3rd. Limited EOD available.\n\nFees\nStandard fee: Seniors Â£10, Juniors and full time students Â£5\nLate fee and EOD: Seniors Â£12, Juniors and full time students Â£5\n\nAn automatic discount will be applied through the SI Entries system for competitors who have their own SIAC.\n\nEOD Entry\nRegister from 10:00 to 11:30, while maps and start slots available.\nA limited number of SI Air Cards will be available for EOD competitors.\nEOD competitors will be able to use standard SI Cards for conventional punching if all available SI Air Cards have been issued.\n\nStarts\n10:30 to 12:30. Starts within 400m of Assembly.\n\nCourses\nStandard urban courses. Longest course will be about 8Km.\n \nUKOL points\nYou only get UKOL points if you run the correct course for your age class.\n\nUK Urban League\nYou get points in the category you have chosen to run, as long as it is valid for your age class\n\nTwin Peak Competition\nPrizes for the winners of all age classes.\nTo be competitive, enter the same age class each day (e.g. a W50 will enter Course 6 on Saturday and C on Sunday), You can choose to run â€œupâ€.\nYou will not be competitive if you choose to run â€œdownâ€, but you can, of course, do so.\n\nBoth times on Saturday and time on Sunday will be added together to give final Twin Peak placing.\n(For M/W 10 to 14, add together the single time on Saturday and the time on Sunday) ",
    "created_at": "2016-07-18T17:26:48.283Z",
    "updated_at": "2016-07-18T17:26:48.283Z",
    "entity_id": 26,
    "finish": "2016-07-11T00:00:00.000Z",
    "google_id": "h56pf4ai304oq33gv1o24bmnlg@google.com",
    "location": "Brooks, MMU Birley Bonsall Street",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 27,
    "name": "Together in Song",
    "category": "partnership",
    "start": "2016-06-11T14:00:00.000Z",
    "description": "Dementia friendly gospel choir for African and Caribbean people with memory difficulties/dementia to enjoy and spend time together with relatives or friends.\n\nEveryone welcome.\n\nContact: Dorothy Allen Dorothy@togetherdementiasupport.org, Sally Ferris 07854 335890 or Dawn Edge dawn.edge@manchester.ac.uk 07796 202806",
    "created_at": "2016-07-18T17:26:48.297Z",
    "updated_at": "2016-07-18T17:26:48.297Z",
    "entity_id": 27,
    "finish": "2016-06-11T16:00:00.000Z",
    "google_id": "8l5fr4vv5to10t0toggs1om3bk@google.com",
    "location": "Hibiscus Court - Extra Care Retirement Apartments, 16 Sedgeborough Rd, Manchester M16 7HU, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 28,
    "name": "Together in Song",
    "category": "partnership",
    "start": "2016-10-15T14:00:00.000Z",
    "description": "Dementia friendly gospel choir for African and Caribbean people with memory difficulties/dementia to enjoy and spend time together with relatives or friends.\n\nEveryone welcome.\n\nContact: Dorothy Allen Dorothy@togetherdementiasupport.org, Sally Ferris 07854 335890 or Dawn Edge dawn.edge@manchester.ac.uk 07796 202806",
    "created_at": "2016-07-18T17:26:48.313Z",
    "updated_at": "2016-07-18T17:26:48.313Z",
    "entity_id": 28,
    "finish": "2016-10-15T16:00:00.000Z",
    "google_id": "20i9p5qdohcfn6crsptu9nf33g@google.com",
    "location": "Hibiscus Court - Extra Care Retirement Apartments, 16 Sedgeborough Rd, Manchester M16 7HU, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 29,
    "name": "Together in Song",
    "category": "partnership",
    "start": "2016-09-17T14:00:00.000Z",
    "description": "Dementia friendly gospel choir for African and Caribbean people with memory difficulties/dementia to enjoy and spend time together with relatives or friends.\n\nEveryone welcome.\n\nContact: Dorothy Allen Dorothy@togetherdementiasupport.org, Sally Ferris 07854 335890 or Dawn Edge dawn.edge@manchester.ac.uk 07796 202806",
    "created_at": "2016-07-18T17:26:48.330Z",
    "updated_at": "2016-07-18T17:26:48.330Z",
    "entity_id": 29,
    "finish": "2016-09-17T16:00:00.000Z",
    "google_id": "17b0apo0hj3ruoih6t1r6ngo04@google.com",
    "location": "Hibiscus Court - Extra Care Retirement Apartments, 16 Sedgeborough Rd, Manchester M16 7HU, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 30,
    "name": "Together in Song",
    "category": "partnership",
    "start": "2016-08-13T14:00:00.000Z",
    "description": "Dementia friendly gospel choir for African and Caribbean people with memory difficulties/dementia to enjoy and spend time together with relatives or friends.\n\nEveryone welcome.\n\nContact: Dorothy Allen Dorothy@togetherdementiasupport.org, Sally Ferris 07854 335890 or Dawn Edge dawn.edge@manchester.ac.uk 07796 202806",
    "created_at": "2016-07-18T17:26:48.361Z",
    "updated_at": "2016-07-18T17:26:48.361Z",
    "entity_id": 30,
    "finish": "2016-08-13T15:00:00.000Z",
    "google_id": "r5q1733g2bvresv3mhq6prsii4@google.com",
    "location": "Hibiscus Court - Extra Care Retirement Apartments, 16 Sedgeborough Rd, Manchester M16 7HU, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 31,
    "name": "Together in Song",
    "category": "partnership",
    "start": "2016-07-09T14:00:00.000Z",
    "description": "Dementia friendly gospel choir for African and Caribbean people with memory difficulties/dementia to enjoy and spend time together with relatives or friends.\n\nEveryone welcome.\n\nContact: Dorothy Allen Dorothy@togetherdementiasupport.org, Sally Ferris 07854 335890 or Dawn Edge dawn.edge@manchester.ac.uk 07796 202806",
    "created_at": "2016-07-18T17:26:48.385Z",
    "updated_at": "2016-07-18T17:26:48.385Z",
    "entity_id": 31,
    "finish": "2016-07-09T16:00:00.000Z",
    "google_id": "qug0u0p9mao9b5r1bjhb7p2i0g@google.com",
    "location": "Hibiscus Court - Extra Care Retirement Apartments, 16 Sedgeborough Rd, Manchester M16 7HU, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 32,
    "name": "Powerhouse Library",
    "category": "partnership",
    "start": "2016-04-21T10:00:00.000Z",
    "description": "Monday: 11am-2pm \nTuesday: 11am-2pm\nWednesday: 11am-2pm\nThursday: 11am -2pm\nFriday: closed\nSaturday: 12-5pm\nSunday: Closed\n\nCall: 0161 227 3758\nEmail: powerhouselibrary@manchester.gov.uk\n",
    "created_at": "2016-07-18T17:26:48.405Z",
    "updated_at": "2016-07-18T17:26:48.405Z",
    "entity_id": 32,
    "finish": "2016-04-21T13:00:00.000Z",
    "google_id": "c9ahuoa9lnl137ntm008rtgtrc@google.com",
    "location": "Moss Side Powerhouse Library, 140 Raby St, Manchester M14 4SQ, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 33,
    "name": "Hulme Library",
    "category": "partnership",
    "start": "2016-04-20T12:00:00.000Z",
    "description": "Hulme had the very first branch library of Manchesterâ€™s free library â€“ which was itself the countryâ€™s first free library!\n\nAssistance Available:\nMondays: 1â€“5pm\nTuesdays: 9amâ€“1pm\nWednesdays: 1â€“8pm\nThursdays: 9am-1pm\nFridays: 1â€“5pm\nSaturdays: 9am-1pm & 2â€“5pm\nBank holidays we are closed.\n\nThere is underground car parking\n\nThe library will be open the same hours as the leisure centre and you will be able to:\nbrowse & borrow a selection of popular books;\nreturn & renew books;\nlog on to internet-ready PCs; and \ncollect reservations.\nContact: 0161 227 3739 or hulmelibrary@manchester.gov.uk",
    "created_at": "2016-07-18T17:26:48.425Z",
    "updated_at": "2016-07-18T17:26:48.425Z",
    "entity_id": 33,
    "finish": "2016-04-20T19:00:00.000Z",
    "google_id": "uvj7ciu79208kssph3rfap6qv4@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 34,
    "name": "Hulme Library",
    "category": "partnership",
    "start": "2016-04-23T13:00:00.000Z",
    "description": "Hulme had the very first branch library of Manchesterâ€™s free library â€“ which was itself the countryâ€™s first free library!\n\nAssistance Available:\nMondays: 1â€“5pm\nTuesdays: 9amâ€“1pm\nWednesdays: 1â€“8pm\nThursdays: 9am-1pm\nFridays: 1â€“5pm\nSaturdays: 9am-1pm & 2â€“5pm\nBank holidays we are closed.\n\nThere is underground car parking\n\nThe library will be open the same hours as the leisure centre and you will be able to:\nbrowse & borrow a selection of popular books;\nreturn & renew books;\nlog on to internet-ready PCs; and \ncollect reservations.\nContact: 0161 227 3739 or hulmelibrary@manchester.gov.uk",
    "created_at": "2016-07-18T17:26:48.446Z",
    "updated_at": "2016-07-18T17:26:48.446Z",
    "entity_id": 34,
    "finish": "2016-04-23T16:00:00.000Z",
    "google_id": "dful56j9cu09kdnofscgs7ffeg@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 51,
    "name": "Barnados Womens Group",
    "category": "partnership",
    "start": "2016-03-10T16:30:00.000Z",
    "description": "Barnados Womens Group\n4:30pm â€“ 7:30pm\nFree\nZion Centre\n339 Stretford Road\nManchester M15 4ZY\nTel: 0161 226 5412\nwww.zioncentre.co.uk\n",
    "created_at": "2016-07-18T17:26:48.763Z",
    "updated_at": "2016-07-18T17:26:48.763Z",
    "entity_id": 51,
    "finish": "2016-03-10T19:30:00.000Z",
    "google_id": "rsoh6g03g1u19rh7iroerji5mc@google.com",
    "location": "Zion Community Resource Centre, 339 Stratford, Manchester, Manchester M15 4ZY, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 96,
    "name": "Tea Break Club",
    "category": "partnership",
    "start": "2016-02-15T13:00:00.000Z",
    "description": "Contact Anne for more information:\n0161 226 8254\nanne389@btinternet.com",
    "created_at": "2016-07-18T17:26:49.544Z",
    "updated_at": "2016-07-18T17:26:49.544Z",
    "entity_id": 96,
    "finish": "2016-02-15T13:45:00.000Z",
    "google_id": "fro63veov8mqgv5cimhgeenfac@google.com",
    "location": "Aqarius Centre, 21 Eden Close, M15 6AX",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 97,
    "name": "Art Class",
    "category": "partnership",
    "start": "2016-02-09T11:00:00.000Z",
    "description": "Contact Anne for more information:\n0161 226 8254\nanne389@btinternet.com",
    "created_at": "2016-07-18T17:26:49.572Z",
    "updated_at": "2016-07-18T17:26:49.572Z",
    "entity_id": 97,
    "finish": "2016-02-09T13:00:00.000Z",
    "google_id": "4tnq09db23i8vgim0uf3vfqjo4@google.com",
    "location": "Aqarius Centre, 21 Eden Close, M15 6AX",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 37,
    "name": "Community Learning Festival",
    "category": "partnership",
    "start": "2016-07-26T00:00:00.000Z",
    "description": "This Community Learning Festival consists of four days of workshops, speakers and events to inspire and support many types of learning. It will also provide a space to build connections between people, and between the University and our local community.\n\nTuesday: Theme - Politics and Democracy\n12 noon Drumming workshop and Spoken Word event led by Emeka\nElendu and Joy Jikiemi\n1.00pm - 2.30pm Community Philosophy: Peaceful Cities? Peaceful World?\nChildren and young peopleâ€™s workshop led by Graeme Tiffany with\nHideaway\n1.00pm - 2.30pm Peopleâ€™s History of Hulme and Moss Side: All age walk with\nDominique Tessier\n2.45pm - 3.45pm Community Philosophy: Peaceful Neighbourhoods? Peaceful\nWorld? All age workshop led by Graeme Tiffany\n2.45pm - 3.45pm Peopleâ€™s History walk: Children and young peopleâ€™s walk with\nDominique Tessier\n4.00pm - 5.00pm Young people interview local Councillors (facilitated by Hideaway)\n5.00pm Public Lecture with Dr Patrick Williams: The same as it ever was!\nThe Policing of â€˜suspectedâ€™ communities: a focus on the continuities of\nStop and Search.\n6.00pm - 7.00pm Drumming Workshop and Spoken Word performance\n\nTo keep up to date with the festival please subscribe to our email list here.\nhttp://eepurl.com/bOjsCn\n\nThe festival will run from 26th-29th July, to get involved in the planning of the event please email edlab@mmu.ac.uk letting us know how you or your group would want to contribute.",
    "created_at": "2016-07-18T17:26:48.520Z",
    "updated_at": "2016-07-18T17:26:48.520Z",
    "entity_id": 37,
    "finish": "2016-07-27T00:00:00.000Z",
    "google_id": "tnu98on6c865jp309g4ir5spto@google.com",
    "location": "Brooks Building, Birley, Bonsall St, Manchester M15",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 38,
    "name": "Hulme Library",
    "category": "partnership",
    "start": "2016-04-19T08:00:00.000Z",
    "description": "Hulme had the very first branch library of Manchesterâ€™s free library â€“ which was itself the countryâ€™s first free library!\n\nAssistance Available:\nMondays: 1â€“5pm\nTuesdays: 9amâ€“1pm\nWednesdays: 1â€“8pm\nThursdays: 9am-1pm\nFridays: 1â€“5pm\nSaturdays: 9am-1pm & 2â€“5pm\nBank holidays we are closed.\n\nThere is underground car parking\n\nThe library will be open the same hours as the leisure centre and you will be able to:\nbrowse & borrow a selection of popular books;\nreturn & renew books;\nlog on to internet-ready PCs; and \ncollect reservations.\nContact: 0161 227 3739 or hulmelibrary@manchester.gov.uk",
    "created_at": "2016-07-18T17:26:48.542Z",
    "updated_at": "2016-07-18T17:26:48.542Z",
    "entity_id": 38,
    "finish": "2016-04-19T12:00:00.000Z",
    "google_id": "isbg5oeqfhrrq22k7nn48363ak@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 39,
    "name": "Trinity House Opening Party!",
    "category": "partnership",
    "start": "2016-06-03T11:00:00.000Z",
    "description": "Event to celebrate the re-opening of Trinity House!\nMore details to come!\n\nContact: Lydia on 0161 225 1064 or email info@trinityhousecrc.org.uk ",
    "created_at": "2016-07-18T17:26:48.559Z",
    "updated_at": "2016-07-18T17:26:48.559Z",
    "entity_id": 39,
    "finish": "2016-06-03T14:00:00.000Z",
    "google_id": "fe1bpddo56210crdqjcbeebmqo@google.com",
    "location": "Trinity House Community Resource Centr, Grove Close, off Platt Lane Rusholme Manchester M14 5AA",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 40,
    "name": "LGBT Swimming - Northern Wave",
    "category": "partnership",
    "start": "2016-03-15T20:00:00.000Z",
    "description": "For all levels of ability, from beginners and improvers through to masters. A friendly bunch with regular social events, great coaching, overseas trips and a nice atmosphere. The skyâ€™s the limit!\n\nPRICES\nDoor Price: Â£4.50 / session\nStanding Order: Â£15 / month\nConcession â€” door price is Â£2.50 / session or Â£7.50 / month via standing order.\nSee here fore more details: http://northernwave.org/V02/#swimtimes ",
    "created_at": "2016-07-18T17:26:48.573Z",
    "updated_at": "2016-07-18T17:26:48.573Z",
    "entity_id": 40,
    "finish": "2016-03-15T21:00:00.000Z",
    "google_id": "m0dgjnna49tn5v65jjnv3e8c4c@google.com",
    "location": "Moss Side Leisure Centre, Moss Ln E, Moss Side, Manchester M15 5NN, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 41,
    "name": "Coffee Morning",
    "category": "partnership",
    "start": "2016-03-14T10:00:00.000Z",
    "description": "Coffee Morning (Food\nvoucher service)\n10:00am  12:00pm\nZion Centre\n339 Stretford Road\nManchester M15 4ZY\nTel: 0161 226 5412\nwww.zioncentre.co.uk",
    "created_at": "2016-07-18T17:26:48.591Z",
    "updated_at": "2016-07-18T17:26:48.591Z",
    "entity_id": 41,
    "finish": "2016-03-14T12:00:00.000Z",
    "google_id": "d96plvr7dk2t3vf1svv5beasq0@google.com",
    "location": "Zion Community Resource Centre, 339 Stretford Rd, Manchester M15 4ZY, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 42,
    "name": "Flex it at 50",
    "category": "partnership",
    "start": "2016-03-12T10:00:00.000Z",
    "description": "Flex it @ 50\n10.15am â€“ 11.15pm\nÂ£3.00\nZion Centre\n339 Stretford Road\nManchester M15 4ZY\nTel: 0161 226 5412\nwww.zioncentre.co.uk",
    "created_at": "2016-07-18T17:26:48.607Z",
    "updated_at": "2016-07-18T17:26:48.607Z",
    "entity_id": 42,
    "finish": "2016-03-12T11:30:00.000Z",
    "google_id": "oimq0had02u6imhl59a7b9jqak@google.com",
    "location": "Zion Community Resource Centre, 339 Stratford, Manchester, Manchester M15 4ZY, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 43,
    "name": "Art Group",
    "category": "partnership",
    "start": "2016-03-11T13:30:00.000Z",
    "description": "Art Group\n1:30pm â€“ 3:30pm Free\nZion Centre\n339 Stretford Road\nManchester M15 4ZY\nTel: 0161 226 5412\nwww.zioncentre.co.uk\n",
    "created_at": "2016-07-18T17:26:48.627Z",
    "updated_at": "2016-07-18T17:26:48.627Z",
    "entity_id": 43,
    "finish": "2016-03-11T15:30:00.000Z",
    "google_id": "c5pee7m8oedmdijorioqnj0v4s@google.com",
    "location": "Zion Community Resource Centre, 339 Stratford, Manchester, Manchester M15 4ZY, UK",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 44,
    "name": "Flex it at 50",
    "category": "partnership",
    "start": "2016-03-08T12:00:00.000Z",
    "description": "Flex It @ 50\n12:00pm â€“ 1:00pm\nPrice: Â£3\nKath Locke Centre\n123 Moss Lane East\nManchester M15 5DD\nTel: 0161 455 0211\nwww.kathlockecentre.co.uk",
    "created_at": "2016-07-18T17:26:48.646Z",
    "updated_at": "2016-07-18T17:26:48.646Z",
    "entity_id": 44,
    "finish": "2016-03-08T13:00:00.000Z",
    "google_id": "qf5vgun6447fcf89vm3ajcs25g@google.com",
    "location": "Kath Locke Centre, 123 Moss Ln E, Manchester M15 5DD, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  },
  {
    "id": 45,
    "name": "Bingo",
    "category": "partnership",
    "start": "2016-03-09T14:00:00.000Z",
    "description": "Bingo\n2:00pm â€“ 4:00pm\nPrice: Â£3.00 per session\nZion Centre\n339 Stretford Road\nManchester M15 4ZY\nTel: 0161 226 5412\nwww.zioncentre.co.uk\n",
    "created_at": "2016-07-18T17:26:48.662Z",
    "updated_at": "2016-07-18T17:26:48.662Z",
    "entity_id": 45,
    "finish": "2016-03-09T16:00:00.000Z",
    "google_id": "l0llfohqcu9ql3iakfs0oqert0@google.com",
    "location": "Zion Community Resource Centre, 339 Stretford Rd, Manchester M15 4ZY, United Kingdom",
    "latitude": null,
    "longitude": null,
    "event_type": null,
    "event_type_other": null
  }
]
